# https://github.com/marketplace/actions/github-pages-action#table-of-contents

name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '12.x'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.yarn
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # see: https://github.com/marketplace/actions/github-action-for-yarn
      - name: Install node dependencies
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install # will run `yarn install` command

      - name: Docs buildV
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: docs:build # will run `yarn docs:build` command

      - name: Deployment
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vuepress/dist